Add Google Cloud Storage Cache
sh4nks/flask-caching pull request #214
Opened 2021-02-03 21:47 UTC by oittaa

This is useful in cloud environments where shared disk cache doesn't exist, but the computation takes a lot of resources and the resulted data doesn't fit easily in Memcached or Redis.

I used an abandoned S3 pull request as a starting point. https://github.com/pallets/cachelib/pull/6

2021-02-04 02:09 UTC, oittaa commented
All tests passed with my test server.

`GCS_BUCKET=my-test-bucket python3 -m pytest`

```
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_get_dict PASSED                                                                                                     [ 56%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_set_get PASSED                                                                                                      [ 56%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_get_set PASSED                                                                                                      [ 57%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_get_many PASSED                                                                                                     [ 57%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_set_many PASSED                                                                                                     [ 58%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_add PASSED                                                                                                          [ 58%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_delete PASSED                                                                                                       [ 59%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_delete_many PASSED                                                                                                  [ 59%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_inc_dec PASSED                                                                                                      [ 60%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_true_false PASSED                                                                                                   [ 60%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_timeout PASSED                                                                                                      [ 61%]
tests/test_backend_cache.py::TestGoogleCloudStorageCache::test_generic_has PASSED                                                                                                          [ 61%]
```

2021-02-04 15:13 UTC, oittaa commented
For better code coverage you'll need to configure proper Cloud Storage support to your Travis instance.

2021-03-04 13:54 UTC, sh4nks commented
Hi @oittaa, could you rebase your PR against current master and move your backend to ``flask_caching.contrib``?

2021-03-04 15:02 UTC, oittaa commented
Sure thing!

2021-03-04 18:18 UTC, oittaa commented
Please, tell me if something needs to be changed, but this pull request should be rebased now.

2021-03-05 07:19 UTC, sh4nks requested changes
I made some comments on your PR. Would be cool if you could address the issues I have with this PR.

2021-03-05 07:19 UTC, sh4nks commented on tests/conftest.py
> +
While I really like tests, I don't think that they should be included in the official test suite as we would have to maintain them here.

2021-03-05 15:56 UTC, oittaa commented
Removed. You still might want to add a test like I had before. For example JSON can't handle byte strings and they need to be handled as a special case.

```
    def test_generic_get_binary(self, c):
        assert c.set("foo", b"bar")
        assert c.get("foo") == b"bar"
```

2021-03-06 07:26 UTC, sh4nks commented
> Removed. You still might want to add a test like I had before. For example JSON can't handle byte strings and they need to be handled as a special case.
> 
> ```
>     def test_generic_get_binary(self, c):
>         assert c.set("foo", b"bar")
>         assert c.get("foo") == b"bar"
> ```

Feel free to open a new PR for this!

2021-03-06 07:27 UTC, sh4nks approved these changes

2021-03-06 07:28 UTC, merged